# Generated by Django 4.0.6 on 2022-07-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_final_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passed_tests_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank_place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
