# Generated by Django 4.0.6 on 2022-07-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['rank_place']},
        ),
    ]
