# Generated by Django 4.0.6 on 2022-07-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_final_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-final_score']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank_place',
        ),
    ]
