# Generated by Django 4.0.6 on 2022-07-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0010_remove_quiz_groups'),
        ('users', '0009_alter_user_options_remove_user_rank_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-passed_tests_number', '-final_score']},
        ),
        migrations.AddField(
            model_name='user',
            name='passed_tests',
            field=models.ManyToManyField(null=True, related_name='passed_user_set', to='quizes.quiz'),
        ),
    ]
