# Generated by Django 4.0.6 on 2022-07-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0012_remove_questionresult_quiz_result_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_alter_user_options_user_passed_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passed_tests',
            field=models.ManyToManyField(blank=True, null=True, related_name='passed_user_set', to='quizes.quiz'),
        ),
    ]
