# Generated by Django 4.0.6 on 2022-07-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_groups_alter_user_passed_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_rank_place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_place',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
