# Generated by Django 4.0.6 on 2022-07-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_group_rank_place_user_rank_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank_place',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
