# Generated by Django 4.0.6 on 2022-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_group_rank_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='final_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
