# Generated by Django 4.0.6 on 2022-07-27 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_final_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank_place',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
