# Generated by Django 4.0.6 on 2022-07-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_group_rank_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['rank_place']},
        ),
    ]
