# Generated by Django 4.0.6 on 2022-07-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions_number',
        ),
    ]
