# Generated by Django 4.0.6 on 2022-07-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_quiz_questions_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
