# Generated by Django 4.0.6 on 2022-07-22 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0006_alter_question_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresult',
            name='group',
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='group',
        ),
        migrations.RemoveField(
            model_name='quizresult',
            name='quiz',
        ),
        migrations.AddField(
            model_name='questionresult',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_result_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
