# Generated by Django 4.0.6 on 2022-07-22 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('quizes', '0008_questionresult_quiz_quizresult_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresult',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_result_group', to='auth.group'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_result_group', to='auth.group'),
        ),
    ]
