# Generated by Django 4.0.6 on 2022-07-28 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0014_quiz_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
